export const ADD_TO_CART =  "ADD_TO_CART";
export const REMOVE_FROM_CART =  "REMOVE_FROM_CART";

export const ADD_SHIPPING_INFO =  "SAVE_SHIPPING_INFO";
export const UPDATE_SHIPPING_INFO =  "UPDATE_SHIPPING_INFO";
export const DELETE_SHIPPING_INFO =  "DELETE_SHIPPING_INFO";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO"